export const SIM_CORE_VERSION = '0.0.0';
export { Prng } from './rng/Prng';
export { StateHasher } from './replay/StateHasher';
export { loadRapier, rapierVersion } from './physics/rapier';
export { PhysicsWorld } from './physics/PhysicsWorld';
export type { BodyId, BodyState, DebugBuffers } from './physics/PhysicsWorld';
export { parseWorldFile, buildWorld, WorldFileError } from './world/WorldFile';
export type { WorldFile, WorldBox } from './world/WorldFile';
export { InputLog } from './replay/InputLog';
export type { InputFrame, LoggedTick } from './replay/InputLog';
export { World } from './world/World';
export type { WorldOptions } from './world/World';
export type { Face, Rotation, FootprintCell, ChannelDef, JointSpec, ColliderSpec, SpriteSpec, PartDef } from './parts/types';
export { FACES, ROTATIONS, faceDir, opposite, rotateFace, rotateCell, rotationRadians } from './parts/faces';
export { parsePartDef, PartDefError } from './parts/parsePartDef';
export { PartRegistry, defaultRegistry } from './parts/registry';
