import type { LegendEntry } from './types';

/**
 * Shipped tokens. Arrow tokens point the way the part acts: thrust direction, lift direction, release direction,
 * the side the wheel sits on relative to what it mounts to, or the side a rotator carries its turret on.
 */
export const DEFAULT_LEGEND: Readonly<Record<string, LegendEntry>> = {
  C: { part: 'core' },
  F: { part: 'frame' },
  B: { part: 'battery' },
  Z: { part: 'densebattery' },
  E: { part: 'cell' },
  X: { part: 'warhead' },
  G: { part: 'gyro' },
  W: { part: 'wheel', rot: 0 },
  'W^': { part: 'wheel', rot: 180 },
  'W<': { part: 'wheel', rot: 270 },
  'W>': { part: 'wheel', rot: 90 },
  'T^': { part: 'thruster', rot: 0 },
  Tv: { part: 'thruster', rot: 180 },
  'T<': { part: 'thruster', rot: 90 },
  'T>': { part: 'thruster', rot: 270 },
  P: { part: 'propeller', rot: 0 },
  Pv: { part: 'propeller', rot: 180 },
  D: { part: 'decoupler', rot: 0 },
  Dv: { part: 'decoupler', rot: 180 },
  'D<': { part: 'decoupler', rot: 90 },
  'D>': { part: 'decoupler', rot: 270 },
  O: { part: 'radar' },
  'K^': { part: 'booster', rot: 0 },
  Kv: { part: 'booster', rot: 180 },
  'K<': { part: 'booster', rot: 90 },
  'K>': { part: 'booster', rot: 270 },
  H: { part: 'heavywarhead' },
  Y: { part: 'heavygyro' },
  'S^': { part: 'seeker', rot: 0 },
  Sv: { part: 'seeker', rot: 180 },
  'S<': { part: 'seeker', rot: 90 },
  'S>': { part: 'seeker', rot: 270 },
  'Q^': { part: 'flare', rot: 0 },
  Qv: { part: 'flare', rot: 180 },
  'Q<': { part: 'flare', rot: 90 },
  'Q>': { part: 'flare', rot: 270 },
  'M^': { part: 'gun', rot: 0 },
  Mv: { part: 'gun', rot: 180 },
  'M<': { part: 'gun', rot: 90 },
  'M>': { part: 'gun', rot: 270 },
  A: { part: 'armorplate' },
  So: { part: 'solar', rot: 0 },
  'V^': { part: 'swivelthruster', rot: 0 },
  Vv: { part: 'swivelthruster', rot: 180 },
  'V<': { part: 'swivelthruster', rot: 90 },
  'V>': { part: 'swivelthruster', rot: 270 },
  'L^': { part: 'fin', rot: 0 },
  Lv: { part: 'fin', rot: 180 },
  'L<': { part: 'fin', rot: 90 },
  'L>': { part: 'fin', rot: 270 },
  Xm: { part: 'mine' },
  N: { part: 'radio' },
  J: { part: 'jammer' },
  U: { part: 'smoke' },
  'Gp^': { part: 'grapple', rot: 0 },
  Gpv: { part: 'grapple', rot: 180 },
  'Gp<': { part: 'grapple', rot: 90 },
  'Gp>': { part: 'grapple', rot: 270 },
  R: { part: 'rotator', rot: 0 },
  Rv: { part: 'rotator', rot: 180 },
  'R<': { part: 'rotator', rot: 90 },
  'R>': { part: 'rotator', rot: 270 },
};
